[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12
decorations = "Buttonless"
opacity = 0.95
blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 13

[general]
import = [
    "~/.config/alacritty/catppuccino-mocha.toml"
]

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"
